name: Deploy Docker

on:
  push:
    branches:
      - migrate-to-gh-actions
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master
      - gh-actions*
      - migrate-to-gh-actions
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile-extension: ""
            dockerimage-suffix: ""
          - dockerfile-extension: ".gcc"
            dockerimage-suffix: "-gcc"
    steps:
      - uses: actions/checkout@v2.3.4
#      - name: Log in to GH registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Create docker images based on Dockerfile${{ matrix.dockerfile-extension }}
        run: script/docker-deploy "Dockerfile${{ matrix.dockerfile-extension }}" "$GITHUB_REF" "${{ matrix.dockerimage-suffix }}" "${{ secrets.GITHUB_TOKEN }}" "${{ github.actor }}"
        env:
          DOCKER_IMAGE: stodevx/stograde
