name: Deploy Docker

on:
  push:
    branches:
      - migrate-to-gh-actions
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master
      - gh-actions*
      - migrate-to-gh-actions
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Log in to GH registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Create docker images based on python 3-slim
        run: script/docker-deploy Dockerfile "$GITHUB_REF"
        env:
          DOCKER_IMAGE: stodevx/stograde
      - name: Create docker images based on gcc latest
        run: script/docker-deploy Dockerfile.gcc "$GITHUB_REF" "-gcc"
        env:
          DOCKER_IMAGE: stodevx/stograde
