name: Deploy Docker

on:
  push:
    branches:
      - migrate-to-gh-actions
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master
      - gh-actions*
      - migrate-to-gh-actions
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile-extension: ""
            dockerimage-suffix: ""
          - dockerfile-extension: ".gcc"
            dockerimage-suffix: "-gcc"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to GH registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine tags
        id: docker-tags
        run: script/docker-tags.bash "$GITHUB_REF" "${{ matrix.dockerimage-suffix }}"
      - name: Build and push with tags ${{ steps.docker-tags.output }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile${{ matrix.dockerfile-extension }}
          platforms: linux/arm/v7,linux/amd64
          push: true
          tags: ${{ steps.docker-tags.output }}

#      - name: Log in to GH registry
#        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
#      - name: Create docker images based on Dockerfile${{ matrix.dockerfile-extension }}
#        run: script/docker-deploy "Dockerfile${{ matrix.dockerfile-extension }}" "$GITHUB_REF" "${{ matrix.dockerimage-suffix }}"
#        env:
#          DOCKER_IMAGE: stodevx/stograde
#          GITHUB_ACTOR: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
