name: PyPi Deploy

on:
#  push:
#    branches:
#      - migrate-to-gh-actions
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    tags:
      - v*

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build --user
      - name: Build package
        run:
          python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
